### ISSUE TITLE
Link to Project Meteor is broken 

### ISSUE THREAD

**Issue by mayaCostantini** [AICoE/manage-dependencies-tutorial#19]
**Describe the bug**
The link to use Project Meteor on Operate First is broken in the "Project Meteor" section of the share-your-work.md file.

**To Reproduce**
Go to http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud/

**Expected behavior**
The link redirects to Project Meteor on Operate First.

**Screenshots**
![Screenshot from 2021-10-18 09-45-24](https://user-images.githubusercontent.com/66788861/137689290-e845484e-28cd-455b-b48a-6f42b3870515.png)

**Comment by tumido** [comment]
Working on deploying meteor to Smaug today. :+1:
