### ISSUE TITLE
Please add documentation for how to set up environment if receiving a reproducible notebook.  

### ISSUE THREAD

**Issue by MichaelClifford** [AICoE/manage-dependencies-tutorial#21]
Current docs focus on how to set up a reproducible notebook. Can you also include instruction for a user who is receiving a reproducible notebook. 

* What baseline requirements do they need in their JH image to use the notebook metadata to set up their environment? (jupyterlab and jupyterlab-requirements minimum versions)  
* What CLI commands do they need to run to create a new kernel? 
* How do they make sure the notebook is set to the new kernel? 
* How do they clean up/ remove the new kernel?

**Comment by pacospace** [comment]
> Current docs focus on how to set up a reproducible notebook. Can you also include instruction for a user who is receiving a reproducible notebook.
> 
> * What baseline requirements do they need in their JH image to use the notebook metadata to set up their environment? (jupyterlab and jupyterlab-requirements minimum versions)
> * What CLI commands do they need to run to create a new kernel?
> * How do they make sure the notebook is set to the new kernel?
> * How do they clean up/ remove the new kernel?

Thanks @MichaelClifford, this would be a great addition!

**Comment by pacospace** [comment]
We can close this, it was solved by linked PRs.
